default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: <%= ENV['CONTACT_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['CONTACT_APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: contact_app_development

test:
  <<: *default
  database: contact_app_test

production:
  <<: *default
  database: contact_app_production
  username: <%= ENV['CONTACT_APP_DATABASE_USERNAME_PROD'] %>
  password: <%= ENV['CONTACT_APP_DATABASE_PASSWORD_PROD'] %>
